E-Commerce/gurukripa/urls.py
from django.contrib import admin
from django.urls import path, include
from myapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
]

E-Commerce/myapp/urls.py
from django.contrib import admin
from django.urls import path
from myapp import views
from gurukripa  import settings
from django.conf.urls.static import static
from .views import Index, Cart, Checkout, OrderView, Login
from .middlewares.auth import auth_middleware


app_name = 'myapp' 
urlpatterns = [
    path('', Index.as_view(), name="index"),
    path('item/<int:item_id>/', views.detail, name="detail"),
    path('add_item/', views.add_item, name="add_item"),
    path('cart/', Cart.as_view(), name="cart"),
    path('check-out/', Checkout.as_view(), name="checkout"),
    path('orders/', auth_middleware(OrderView.as_view()), name="orders"),
    path('login/', Login.as_view(), name = "login"),
    path("signup/", views.signup, name="signup"),
    path('logout/', views.logout, name="logout"),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

E-Commerce/myapp/models.py
from django.db import models
import datetime
from django.contrib.auth.models import User, auth

# Create your models here.
class category(models.Model):
    def __str__(self):
        return self.name
    
    @staticmethod 
    def get_all_category():
        return category.objects.all()

    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100)



class item(models.Model):
    def __str__(self):
        return self.name
    
    id = models.AutoField(primary_key=True)
    name= models.CharField(max_length=100)
    desc= models.CharField(max_length=500, null=True, blank=True)
    price= models.IntegerField()
    category = models.ForeignKey(category, on_delete=models.CASCADE, default=1 )
    item_image= models.ImageField(default='default.jpg', upload_to='item_images/')


    @staticmethod
    def get_items_by_id(ids):
        return item.objects.filter(id__in = ids)
    
    @staticmethod
    def get_all_items():
        return item.objects.all()

    @staticmethod
    def get_all_items_by_category_id(category_id):
        if category_id:
            return item.objects.filter(category=category_id)
        else:
            return item.get_all_items()

class Customer(models.Model):
    
    def __str__(self):
        return self.first_name
    

    id = models.AutoField(primary_key=True)
    first_name= models.CharField(max_length=100)            
    last_name= models.CharField(max_length=100)
    phone= models.CharField(max_length=15)
    email = models.EmailField()
    password = models.CharField(max_length=500)


    def register(self):
        self.save()

    @staticmethod
    def get_customer_by_email(email):
        try:
            return Customer.objects.get(email = email)
        except:
            return False
        

    def isExists(self):
        if Customer.objects.filter(email = self.email):
            return True

        return False



class Order(models.Model):

    id = models.AutoField(primary_key=True)
    item = models.ForeignKey(item, on_delete=models.CASCADE)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE,null=True)
    quantity = models.IntegerField(default=1, null=True)
    price = models.IntegerField()
    address = models.CharField(max_length=500, null=True)
    phone = models.CharField(max_length=10, null=True)
    date = models.DateTimeField(default=datetime.datetime.today)
    status = models.BooleanField(default=False)
    

   
    def placeOrder(self):
        self.save()

    @staticmethod
    def get_orders_by_customer(customer_id):
        return Order\
            .objects\
            .filter(customer = customer_id)\
            .order_by('-date')    

E-Commerce/myapp/views.py
from django.shortcuts import render,redirect, HttpResponseRedirect
from django.http import HttpResponse
from .models import item,category,Order, Customer
from django.contrib.auth.models import User, auth
from django.contrib.auth.hashers import make_password, check_password
from django.contrib import messages
from django.views.generic import ListView
from django.views import View




# Create your views here.
class Index(View):

    def post(self, request):
        item = request.POST.get('item')
        remove =request.POST.get('remove')
        cart = request.session.get('cart')
        if cart:
            quantity = cart.get(item)
            if quantity:
                if remove:
                    if quantity <= 1:
                        cart.pop(item)
                    else:    
                        cart[item] = quantity - 1
                else:
                    cart[item] = quantity + 1

            else:
                cart[item] = 1

        else:
            cart = {}
            cart[item] = 1

        request.session['cart'] = cart
        print('cart', request.session['cart'])

        return redirect('/')

    def get(self, request):
        cart = request.session.get('cart')
        if not cart:
            request.session['cart'] = {}
        item_list = None
        category_list = category.get_all_category()
        CategoryID = request.GET.get('category')
        if CategoryID:
            item_list = item.get_all_items_by_category_id(CategoryID)
        else:
            item_list = item.get_all_items()

        context={}
        context['item_list'] = item_list
        context['category_list'] = category_list
        print('You are ', request.session.get('email'))

        return render(request,'myapp/index.html',context)

        def post(self, request):
            item = request.POST.get('item')
            print(item)

def detail(request,item_id):
    Item = item.objects.get(id=item_id)
    return render(request, 'myapp/detail.html',{'item' : Item})

def add_item(request):
    return render(request, 'myapp/add_item.html')


    return render(request, 'myapp/maincode.html')

class Cart(View):

    def get(self, request):
        ids = list(request.session.get('cart').keys())
        items = item.get_items_by_id(ids)
        return render(request,'myapp/cart.html', {'items' : items})

class Checkout(View):
    
    def post(self, request):
        address = request.POST.get('address')
        phone = request.POST.get('phone')
        customer = request.session.get('customer')
        cart = request.session.get('cart')
        items = item.get_items_by_id(list(cart.keys()))
        print(address, phone, customer, cart, items)

        for Item in items:

            order = Order(
                customer = Customer(id = customer),
                item = Item,
                price = Item.price,
                address = address,
                phone = phone,
                quantity = cart.get(str(Item.id)))

            order.save()
        request.session['cart'] = {}

        return redirect('/cart')

class OrderView(View):

    def get(self, request):
        customer = request.session.get('customer')
        orders = Order.get_orders_by_customer(customer)
        print(orders)
        orders = orders.reverse()
        return render(request,'myapp/orders.html',{'orders' : orders})

class Login(View):
    return_url = None
    def get(self, request):
        Login.return_url = request.GET.get('return_url')
        return render(request,'myapp/login.html')

    def post(self, request):
        email = request.POST.get('email')
        password = request.POST.get('password')
        customer = Customer.get_customer_by_email(email)
        error_message = None
        if customer:
            flag = check_password(password, customer.password)
            if flag:
                request.session['customer'] = customer.id
                
                if Login.return_url:
                    return HttpResponseRedirect(Login.return_url)

                else:
                    Login.return_url = None
                    return redirect("/")

            else:
                error_message = 'Email or Password invalid !!!'

        else:
            error_message = 'Email or Password invalid !!!'
        print(email, password)
        return render(request, 'myapp/login.html', {'error' : error_message})

def validateCustomer(customer):
    
    error_message = None

    if (not customer.first_name):
        error_message = "First Name Required !!"
    elif len(customer.first_name) < 4:
        error_message = 'First Name must be 4 char long or more'
    elif not customer.last_name:
        error_message = 'Last Name Required'
    elif len(customer.last_name) < 3:
        error_message = 'Last Name must be 3 char long or more'
    elif not customer.phone:
        error_message = 'Phone Number required'
    elif len(customer.phone) < 10:
        error_message = 'Phone Number must be 10 char Long'
    elif len(customer.password) < 6:
        error_message = 'Password must be 6 char long'
    elif len(customer.email) < 5:
        error_message = 'Email must be 5 char long'
    elif customer.isExists():
        error_message = 'Email Address Already Registered.'

    return error_message    

def registerUser(request):
    
        postData = request.POST
        first_name = postData.get('firstname')
        last_name = postData.get('lastname')
        phone = postData.get('phone')
        email = postData.get('email')
        password = postData.get('password')

        
        #validate 
        value={
            'first_name' : first_name, 
            'last_name' : last_name, 
            'phone' : phone, 
            'email' : email
        }

        error_message = None

        customer = Customer(first_name = first_name, 
                last_name = last_name, 
                phone = phone, 
                email = email, 
                password = password)

        error_message = validateCustomer(customer)

        
       
        #Passing Data and Saving
        if not error_message:
            customer.password = make_password(customer.password)
            customer.register()
            return redirect('/')

        else:   
            data = {
                'error' : error_message,
                'values' : value
            } 
            return render(request, 'myapp/signup.html', data)
     
def signup(request):
    if request.method =='GET':
        return render(request, 'myapp/signup.html')
    else: 
        return registerUser(request)

def logout(request):
    request.session.clear()
    return redirect('/')

E-Commerce/myapp/templates/myapp/add_item.html
<form method="POST" align="center">
    {% csrf_token %}
    <input type="text" name="name" id="name" placeholder="Enter the name of your item"><br>
    <input type="text" name="desc" id="desc" placeholder="Enter the desc of your item"><br>
    <input type="text" name="price" id="price" placeholder="Enter the price of your item"><br>
    <input type="text" name="name" id="name" placeholder="Enter the name of your item"><br>
    <input type="file" name="book_image" id="book_image" placeholder="Enter the name of your item"><br>
    <input type="submit" name="submit" id="submit">
</form>

E-Commerce/myapp/templates/myapp/base.html
{% load static %}
<html>

  <head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'myapp/style.css' %}">
  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
      <div class="container">
        <a class="navbar-brand" href="{% url 'myapp:index' %}">
          <img src="{% static 'logo2.jpg' %}" width="30" height="30" class="d-inline-block align-top" alt="">
          E-Commerce
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
          aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="/">Home</a>
            </li>

            <li class="nav-item">
              <a class="nav-link" href="{% url 'myapp:cart' %}">Cart
                <span class="badge badge-info">{{request.session.cart.keys|length}}</span>
              </a>
            </li>

            {% if request.session.customer %}

            <li class="nav-item">
              <a class="nav-link" href="{% url 'myapp:orders' %}">Orders</a>
            </li>

            <li class="nav-item">
              <a class="nav-link" href="{% url 'myapp:logout' %}">Log Out</a>
            </li>

            {% else %}

            <li class="nav-item">
              <a class="nav-link" href="{% url 'myapp:signup' %}">Signup</a>
            </li>

            <li class="nav-item">
              <a class="nav-link" href="{% url 'myapp:login' %}">Login</a>
            </li>

            {% endif %}


          </ul>
        </div>
      </div>
    </nav>


    {% block body %}

    {% endblock %}

    <!--js bootsrap code-->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
      integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
      integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
      integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous">
    </script>

  </body>

</html>

E-Commerce/myapp/templates/myapp/cart.html
{% extends 'myapp/base.html' %}
{% load static %}
{% block body %}
{% load cart %}
{% load custom_filter %}


<div class="container">
  <div class="border rounded p-4 m-4">
    <p class="display-4 pl-4 ml-4">Your Cart</p>
    <hr>
    <table class="table">
      <thead>
        <tr>
          <th>S.no</th>
          <th>Image
          <th>
          <th>Item Name</th>
          <th>Price</th>
          <th>Quantity</th>
          <th>Total</th>
        </tr>
      </thead>
      <tbody>
        {% for item in items %}

        <tr>
          <td>{{forloop.counter}}</td>
          <td><img src="{{item.item_image.url}}" style="height:50px" class="rounded-circle" alt=""></td>
          <td>{{item.name}}</td>
          <td>{{item.price|currency}}</td>
          <td>{{item|cart_quantity:request.session.cart}}</td>
          <td>{{item|price_total:request.session.cart|currency}}</td>

        </tr>

        {% endfor %}

      </tbody>

      <tfoot>
        <tr>
          <th class="text-center" colspan="4">Total</th>
          <th>{{items|total_cart_price:request.session.cart|currency}}</th>
        </tr>

      </tfoot>
    </table>

    <hr>

    <div class="m-3 p-3">
      <a href="#" data-toggle="modal" data-target="#exampleModal"
        class="btn btn-outline-info border rounded col-lg-3 float-right ">Checkout</a>
    </div>

  </div>
</div>


<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
  aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">CheckOut Form</h5>
        <hr>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <div class="modal-body">
        <div class="m-2 p-2">
          <form action="/check-out/" method="POST">
            {% csrf_token %}
            <div class="form-group">
              <label for="">Address</label>
              <input type="text" name="address" id="address" class="form-control" placeholder="" aria-describedby="helpId">
            </div>
            <div class="form-group">
              <label for="">Phone</label>
              <input type="text" name="phone" id="phone" class="form-control" placeholder="" aria-describedby="helpId">
            </div>
            <input type="submit" class="btn btn-outline-info col-lg-6 float-right" value="Check out">
          </form>
        </div>
      </div>

    </div>
  </div>
</div>

{% endblock %}

E-Commerce/myapp/templates/myapp/detail.html
{% extends 'myapp/base.html' %}
 
{% block body %}
 
<div class="container">
    <div class="row">
        <div class="col-md-6">
                <img width="300" height="300" src="{{item.item_image.url}}">
 
        </div>
        <div class="col-md-6">
                <h2> {{item.name}} </h2>
 
                <h4>{{item.desc}}</h4>
                
                <h6>{{item.price}}</h6>
                               
        </div>
    </div>
</div>
 
 
 
{% endblock %}

E-Commerce/myapp/templates/myapp/index.html
{% extends 'myapp/base.html' %}
{% load static %}
{% block body %}
{% load cart %}
{% load custom_filter %}


<hr>

<!--carousel-->
<div class="container">
  <div class="carousel slide carousel-fade" id="myslider" data-ride="carousel">
    <div class="carousel-inner">

      <div class="carousel-item active">
        <img class="d-block w-100" src="media/wallpaper.jpg" alt="First Slide">
      </div>

      <div class="carousel-item ">
        <img class="d-block w-100" src="media/wallpaper1.jpg" alt="Second Slide">
      </div>

      <div class="carousel-item ">
        <img class="d-block w-100" src="media/wallpaper2.jpg" alt="Third Slide">
      </div>

    </div>

    <ul class="carousel-indicators">

      <li data-target="#myslider" data-slide-to="0" class="active">
      </li>

      <li data-target="#myslider" data-slide-to="1" class="">
      </li>

      <li data-target="#myslider" data-slide-to="2" class="">
      </li>
    </ul>

    <a href="#myslider" data-slide="prev" role="button" class="carousel-control-prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"> </span>
    </a>

    <a href="#myslider" data-slide="next" role="button" class="carousel-control-next">
      <span class="carousel-control-next-icon" aria-hidden="true"> </span>
    </a>

  </div>
</div>

<hr>

<div class="container">
  <h3>New Arrival</h3>
</div>

<hr>

<div class="container">
  <div class="row">
    <!--For displaying categories on the left side of page-->
    <div class="col-lg-3 mx-auto">
      <div class="list-group">
        {% for category in category_list %}
        <a href="/?category={{category.id}}" class="list-group-item list-group-item-action">{{category.name}}</a>
        {% endfor %}
      </div>
    </div>

    <!-- For displaing all items on the screen-->
    <div id='items' class="col-lg-9 mx-auto">
      <div class="row mx-auto">
        {% for item in item_list %}
        <div class="col-md-4"  >
          <div class="card mx-auto mb-5" id={{item.id}}>
            <img src="{{item.item_image.url}}" width="70" height="300" class="card-img-top" alt="">
            <div class="card-body">
              <h5 class="card-title">{{item.name}}</h5>
              <p class="card-text">{{item.price|currency}}</p>
      

                <!-- {{item | is_in_cart:request.session.cart}} -->

              
            </div>
            <div class="card-footer p-0 ">
              
              {% if item|is_in_cart:request.session.cart %}
              <div class="row no-gutters">
                <form action="/#{{item.id}}" class="col-2" style="margin:0px" method="post">
                {% csrf_token %}
                <input hidden type="text" name='item' value='{{item.id}}'>
                <input hidden type="text" name='remove' value='True'>
                <input type="submit" value=" - " class=" btn btn-block btn-secondary">
                </form>
                <div class="text-center col"> {{item|cart_quantity:request.session.cart}} in Cart </div>
                <form action="/#{{item.id}}" class="col-2" style="margin:0px" method="post">
                {% csrf_token %}
                <input hidden type="text" name='item' value='{{item.id}}'>
                <input type="submit" value=" + " class=" btn btn-block btn-secondary">
                </form>
              </div>

              {% else %}

              <form action="/#{{item.id}}" method="POST" class="btn-block" style="margin:0px">
                {% csrf_token %}
                <input hidden type="text" name='item' value='{{item.id}}'>
                <input class="float-right btn btn-light border form-control" type="submit" href="{% url 'myapp:cart' %}" value="Add to Cart">
              </form>

              {% endif %}

              
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
</div>



{% endblock %}

E-Commerce/myapp/templates/myapp/login.html
{% extends 'myapp/base.html' %}
{% load static %}
{% block body %}

<div class="container">
    <div class="m-4 p-4">
        <div class="col-lg-4 mt-4 mb-4 mx-auto border rounded pt-4 ">

            <h3 class="alert alert-light border rounded mt-4 mb-4 ">LogIn Here</h3>

            <form action="/login/" method="post">

                {% csrf_token %}

                {% if error %}

                <div class="alert alert-danger" role="alert">
                    {{error}}
                </div>

                {% endif %}

                <!--Email-->

                <div class="form-group">
                    <label for="">Email</label>
                    <input value="{{values.email}}" type="email" name="email" id="email" class="form-control form-control-sm"
                        placeholder="example@gmail.com" aria-describedby="helpId">
                </div>

                <!--Password-->

                <div class="form-group">
                    <label for="">Password</label>
                    <input type="password" name="password" id="password" class="form-control form-control-sm"
                        placeholder="*******" aria-describedby="helpId">
                </div>

                <!--Submit Button-->

                <div class="form-group">
                    <input class="btn btn-sm btn-info col-lg-4" type="submit" value="Login">
                </div>


            </form>
        </div>
    </div>

</div>

{% endblock %}

E-Commerce/myapp/templates/myapp/orders.html
{% extends 'myapp/base.html' %}
{% block body %}
{% load cart %}
{% load custom_filter %}


<div class="container">
  <div class="border rounded p-4 m-4">
    <p class="display-4 pl-4 ml-4">Your Orders</p>
    <hr>
    <table class="table">
      <thead>
        <tr>
          <th>S.no</th>
          <th>Image</th>
          <th>Item Name</th>
          <th>Date</th>
          <th>Price</th>
          <th>Quantity</th>
          <th>Total</th>
          <th>Status</th>
        </tr>
      </thead>
      <tbody>
        {% for order in orders %}

        <tr>
          <td>{{forloop.counter}}</td>
          <td><img src="{{order.item.item_image.url}}" style="height:50px" class="rounded-circle" alt=""></td>
          <td>{{order.item.name}}</td>
          <td>{{order.date}}</td>
          <td>{{order.price|currency}}</td>
          <td>{{order.quantity}}</td>
          <td>{{order.quantity|multiply:order.price|currency}}</td>
          

          {% if order.status%}

          <td><small class="badge badge-success">Completed</small></td>

          {% else %}

          <td><small class="badge badge-warning">Pending</small></td>

          {% endif %}

        </tr>

        {% endfor %}

      </tbody>
    </table>



  </div>
</div>


{% endblock %}

E-Commerce/myapp/templates/myapp/signup.html
{% extends 'myapp/base.html' %}
{% load static %}
{% block body %}

<div class="container">
    <div class="m-4 p-4">
        <div class="col-lg-5 mx-auto border rounded pt-4 ">

            <h3 class="alert alert-light border rounded">Create An Account</h3>

            <form action="/signup/" method="post">

                {% csrf_token %}

                {% if error %}

                <div class="alert alert-danger" role="alert">
                    {{error}}
                </div>

                {% endif %}

                <!--First Name-->

                <div class="form-group">
                    <label for="">First Name</label>
                    <input value="{{values.first_name}}" type="text" name="firstname" id="firstname" class="form-control form-control-sm"
                        placeholder="First Name" aria-describedby="helpId">
                </div>

                <!--Last Name-->

                <div class="form-group">
                    <label for="">Last Name</label>
                    <input value="{{values.last_name}}" type="text" name="lastname" id="lastname" class="form-control form-control-sm"
                        placeholder="Last Name" aria-describedby="helpId">
                </div>

                <!--Phone Number-->

                <div class="form-group">
                    <label for="">Phone Number</label>
                    <input value="{{values.phone}}" type="number" name="phone" id="phone" class="form-control form-control-sm"
                        placeholder="Phone Number" aria-describedby="helpId">
                </div>

                <!--Email-->

                <div class="form-group">
                    <label for="">Email</label>
                    <input value="{{values.email}}" type="email" name="email" id="email" class="form-control form-control-sm"
                        placeholder="example@gmail.com" aria-describedby="helpId">
                </div>

                <!--Password-->

                <div class="form-group">
                    <label for="">Password</label>
                    <input type="password" name="password" id="password" class="form-control form-control-sm"
                        placeholder="*******" aria-describedby="helpId">
                </div>

                <!--Submit Button-->

                <div class="form-group">
                    <input class="btn btn-sm btn-info" type="submit" value="Create An Account">
                </div>


            </form>
        </div>
    </div>

</div>

{% endblock %}

E-Commerce/myapp/templates/myapp/typeb.html
{% extends 'myapp/base.html' %}
{% block body %}

<div class="container">
   <h3>Typeb</h3>
</div>

<hr>
<div class="container">
    <div class="row">
        {% for typeb in typeb_list %}
            <div class="col-md-3">
                <div class="card">
                    <img src="{{typeb.item_image.url}}" class="card-img-top" alt="">
                      <div class="card-body">
                          <h5 class="card-title">{{typeb.name}}</h5>
                          <p class="card-text">${{typeb.price}}</p>
                          
                      </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>

{% endblock %}                          

E-Commerce/myapp/templates/myapp/typec.html
{% extends 'myapp/base.html' %}
{% block body %}

<div class="container">
   <h3>Typec</h3>
</div>

<hr>
<div class="container">
    <div class="row">
        {% for typec in typec_list %}
            <div class="col-md-3">
                <div class="card">
                    <img src="{{typec.item_image.url}}" class="card-img-top" alt="">
                      <div class="card-body">
                          <h5 class="card-title">{{typec.name}}</h5>
                          <p class="card-text">${{typec.price}}</p>
                          
                      </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>

{% endblock %}                          